<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postNameStripped = $block->stripTags($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
		<h1 class="post-title"><?php echo $_post->getTitle(); ?></h1>
		<div class="blog-post-date">
            <div class="post-info-extra">
                <div class="post-date"><span><span class="icmn-calendar4">&nbsp;</span><?php echo date('F', strtotime($_post->getPublishTime())); ?><?php echo date(' d, Y', strtotime($_post->getPublishTime())); ?></span></div>
            </div>
			<div class="post-info-by">
                <div class="post-by"><span class="icmn-pencil7">&nbsp;</span><span class="title-by"><?php echo __('Post By: ')?></span><span class="name"><?php echo __('Admin')?></span></div>
            </div>
            <div class="post-count-fb-comment-info">
				<span class="icmn-bubble4">&nbsp;</span><span class="comment-title"><?php echo __('Comment')?>: </span><span class="fb-comments-count" data-href="<?php echo $_postUrl ?>"></span>
            </div>
        </div>
		<div class="blog-post-thumb">
			<a href="<?php echo $_post->getPostUrl() ?>">
				<?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
					<?php
						$featuredImgAlt = $_post->getData('featured_img_alt');
					if (!$featuredImgAlt) {
						$featuredImgAlt = $_postNameStripped;
					}
					?>
						<img src="<?= $block->escapeUrl($featuredImage) ?>"
							 alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
				<?php } ?>
			</a> 
		</div> 
		<div class="blog-post-info">	
            <div class="desc">
                <?php echo $block->getContent() ?>
            </div>
			<div class="post-info"> 
				<div class="post-category-name">
					<span class="title-cate"><span class="icmn-folder-open">&nbsp;</span><?php echo __('Category: ')?></span>
					<?php echo $this->getInfoHtml() ?>
				</div>
				<div class="post-header clearfix">
					<div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
						<a class="addthis_button_facebook"></a>
						<a class="addthis_button_twitter"></a>
						<a class="addthis_button_email"></a>
						<a class="addthis_button_compact"></a>
					</div> 
				</div>
			</div>
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>