<div class="block faq-list">
	<div class="list-questions">
		<?php echo $block->getHtmlDataFaq(); ?>
	</div>
</div>
<script type ="text/javascript">
	require(["jquery"], function($){
		$(document).ready(function(){
			$(".question").click(function(){
				if(!$(this).parent().hasClass("select")) {
					$(this).parent().addClass("select");
					$(this).parent().children(".sub-questions").slideDown();
					$(this).parent().children(".answer").slideDown();
				}else {
					$(this).parent().removeClass("select");
					$(this).parent().children(".sub-questions").slideUp();
					$(this).parent().children(".answer").slideUp();
				}
			});
		});
	});
</script>	