<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$helper = $this->helper('Rokanthemes\RokanBase\Helper\Data');
$background = '';
if($helper->getConfigData('themeoption/blogpage/blog_banner_image')){
	$folderName = \Rokanthemes\Themeoption\Model\Config\Bannerblogbackground::UPLOAD_DIR;
	$path = $folderName . '/' . $helper->getConfigData('themeoption/blogpage/blog_banner_image');
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$imageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$path;
	$background = "style='background-image: url(".$imageUrl.");'";
}
?>
<div class="top-banner-blog-container section" <?= $background ?>>
	<div class="top-banner-blog-title container">
		<?= $this->getChildHtml('page.main.title'); ?>
	</div>
</div>