<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar posts list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\AbstractList
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php
    $width = (int)$block->getBlockImageWidth() ?: 300;
    $height = (int)$block->getBlockImageheight() ?: 200;
    $imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<?php if ($_postCollection->count()) { ?>
<div class="sidebar-widget sidebar-post">
	<div class="widget widget-post-tab filter-options-item" data-bind="scope: 'recemt-posts'">
		<div class="filter-options-title"> 
			<?php echo __('Recent Post') ?>
		</div>
		<div class="tab-content filter-options-content">
			<div class="tab-pane fade in active" role="tabpanel">
				<ul class="list-post-tab">
				<?php foreach ($_postCollection as $_post) { ?>
					<?php
						$_postUrl = $block->escapeUrl($_post->getPostUrl());
						$_postName = $block->escapeHtml($_post->getTitle());
					?>
					<li class="item clearfix">
						<?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
						<?php if ($featuredImage) { ?>
							<div class="zoom-image-thumb">
								<?php
								$featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
								if (!$featuredImgAlt) {
									$featuredImgAlt =  $_postName;
								}
								?>
								<a class="post-item-link" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
									<img data-width-amp="<?= $width ?>" data-height-amp="<?= $height ?>" layout="responsive" src="<?= $imageHelper->init($_post->getFeaturedListImg() ?: $_post->getFeaturedImg())->resize($width, $height); ?>"
										 alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
								</a>
							</div>
						<?php } ?>
						<div class="post-tab-info">
						<?php if ($featuredImage && $_post->isPublishDateEnabled()) { ?>
									<span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
							<?php } ?>
							<h3><a class="post-item-link" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
								<?= $_postName ?>
							</a></h3>

							
						</div>
					</li>
				<?php } ?>
				</ul>
			</div>
		</div>
	</div>
</div>
<?php } ?>
