<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('setproduct_config/enable')){?>
	<?php 
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-setproduct section-products-blue"> 
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				// $showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				// $showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			$background = '';
			if($this->getConfig('setproduct_config/background_image')){
				$folderName = \Rokanthemes\Themeoption\Model\Config\Setproductbackground::UPLOAD_DIR;
				$path = $folderName . '/' . $this->getConfig('setproduct_config/background_image');
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
				$imageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$path;
				$background = "style='background-image: url(".$imageUrl.");'";
			}
		?>
		<div class="setproduct">
			<img src="<?php echo $imageUrl ?>" alt="">
			<?php  for($i=1;$i<=3;$i++){ ?>
				<?php  if($this->getConfig('setproduct_'.$i.'/sku')){ ?>
					<?php  
						$_product = $block->loadProduct($this->getConfig('setproduct_'.$i.'/sku'));
						if($_product){ 
					?>
					<?php 
						$style = '';
						if($this->getConfig('setproduct_'.$i.'/custom_css')){
							$style = 'style="'.$this->getConfig('setproduct_'.$i.'/custom_css').'"';
						} 
						$add_class_defaut = '';
						if($this->getConfig('setproduct_config/enable_defaut')){
							if($i == $this->getConfig('setproduct_config/defaut_select')){
								$add_class_defaut = 'active';
							}
						}
					?>					
					<div class="product-item" <?php echo $style ?>>
						<div class="product-icon <?php echo $add_class_defaut ?>"> 
							<a class="view-detail" href="<?php echo $_product->getProductUrl() ?>">
								<?php /* @escapeNotVerified */ echo __('View'); ?>
							</a>
						</div>
						<div class="product">
							<div class="product-item-image">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
							</div>
							<div class="product-item-info product-info">
								<div class="product-top">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<strong class="product name product-item-name product-name">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</strong>
									<div class="product-ratting">
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									</div>
									<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
								</div>
								<div class="view-detail">
									<a class="view-detail-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo __('View Detail'); ?>
									</a>
								</div>
							</div> 
						</div>
					</div>
					<?php } ?>	
				<?php } ?>	
			<?php } ?>
			<script>
				require([
					'jquery',
					'mage/mage'
				], function ($) {
					'use strict';
					$(document).on('click', '.product-icon', function(e) {
						var width_window = $(window).width();
						if(width_window > 991){
							if($(this).closest('.product-icon').hasClass("active")){
								$(this).closest('.product-icon').removeClass("active");
							}else{
								$('.product-icon').removeClass("active");
								$(this).closest('.product-icon').addClass("active"); 
							}
							return false; 
						}
					});
				});
			</script>
		</div>
	</div>
<?php } ?>