<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
?>
<!--deprecated template as image_with_borders is a primary one-->
<img class="photo image"
    src="<?= $block->getImageUrl() ?>"
    loading="lazy"
    width="<?= $block->getWidth() ?>"
    height="<?= $block->getHeight() ?>"
    alt="<?= $block->getLabel() ?>" />
