<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>
<?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
	<label><?php echo __('Categories') ?>: </label>
	<?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
		<a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
		<?php if ($n != $_categoriesCount) { ?>, <?php } ?>
	<?php } ?>
<?php } ?>